# Generated by Django 6.0.3 on 2026-04-11 04:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('shop', 'Shop')], default='customer', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('maDonHang', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayDat', models.DateTimeField(auto_now_add=True)),
                ('anhSanPhamThucTe', models.ImageField(blank=True, null=True, upload_to='order_products/')),
                ('trangThaiDonHang', models.CharField(choices=[('chon_hoa', 'Chọn hoa'), ('dang_thuc_hien', 'Đang thực hiện'), ('hoan_thanh', 'Hoàn thành')], default='chon_hoa', max_length=20)),
                ('ngayGiaoDuKien', models.DateTimeField()),
                ('phiVanChuyen', models.DecimalField(decimal_places=0, max_digits=15)),
                ('anhMauDeXuat', models.ImageField(blank=True, null=True, upload_to='order_proposals/')),
                ('noiDungTuVan', models.TextField(blank=True, null=True)),
                ('trangThai', models.IntegerField(choices=[(1, 'Chờ'), (2, 'Xác nhận'), (0, 'Từ chối')], default=1)),
                ('dipSuDung', models.CharField(max_length=255)),
                ('nganSach', models.DecimalField(decimal_places=0, max_digits=15)),
                ('mauSac', models.CharField(max_length=100)),
                ('thoiGianHoanThanh', models.DateTimeField()),
                ('phongCach', models.CharField(max_length=255)),
                ('ghiChu', models.TextField(blank=True, null=True)),
                ('dia_chi_nhan_hang', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhienChat',
            fields=[
                ('maPhienChat', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trangThai', models.CharField(choices=[('mo', 'Mở'), ('dong', 'Đóng'), ('da_xu_ly', 'Đã xử lý')], default='mo', max_length=20)),
                ('thoiGianTao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('dia_chi_mac_dinh', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TiemHoaProfile',
            fields=[
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shop_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tiemhoa_id', models.CharField(max_length=50, unique=True)),
                ('diaChi', models.TextField()),
                ('moTa', models.TextField(blank=True, null=True)),
                ('maSoThue', models.CharField(max_length=50)),
                ('hinhAnhSanPham', models.ImageField(blank=True, null=True, upload_to='shop_products/')),
                ('logoTiemHoa', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('trangThaiDuyet', models.IntegerField(choices=[(0, 'Chờ duyệt'), (1, 'Đã duyệt'), (2, 'Bị từ chối')], default=0)),
                ('soTaiKhoan', models.CharField(max_length=50)),
                ('tenNganHang', models.CharField(max_length=100)),
                ('tenChuTaiKhoan', models.CharField(max_length=100)),
                ('QR_thanh_toan', models.ImageField(blank=True, null=True, upload_to='shop_qrs/')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('maDanhGia', models.AutoField(primary_key=True, serialize=False)),
                ('soSao', models.IntegerField()),
                ('noiDung', models.TextField()),
                ('hinhAnhThucTe', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('ngayDanhGia', models.DateTimeField(auto_now_add=True)),
                ('maDonHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dv_dathoa.donhang')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('maThanhToan', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tongTien', models.DecimalField(decimal_places=0, max_digits=15)),
                ('noiDung', models.TextField()),
                ('hinhAnhBienLai', models.ImageField(upload_to='payment_receipts/')),
                ('maDonHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dv_dathoa.donhang')),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('maTinNhan', models.AutoField(primary_key=True, serialize=False)),
                ('noiDung', models.TextField()),
                ('hinhAnh', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('thoiGian', models.DateTimeField(auto_now_add=True)),
                ('maPhienChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dv_dathoa.phienchat')),
                ('maTaiKhoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='phienchat',
            name='maKhachHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='dv_dathoa.customerprofile'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dv_dathoa.customerprofile'),
        ),
        migrations.AddField(
            model_name='phienchat',
            name='maTiemHoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='dv_dathoa.tiemhoaprofile'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='tiemhoa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dv_dathoa.tiemhoaprofile'),
        ),
    ]
