# Generated by Django 6.0.3 on 2026-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_dathoa', '0002_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiemhoaprofile',
            name='anh_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tiemhoaprofile',
            name='diemTrungBinh',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tiemhoaprofile',
            name='soDanhGia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiemhoaprofile',
            name='the_loai',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
