# Generated by Django 6.0.3 on 2026-04-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_dathoa', '0003_tiemhoaprofile_anh_url_tiemhoaprofile_diemtrungbinh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='trangThaiDonHang',
            field=models.CharField(choices=[('chon_hoa', 'Chọn hoa'), ('cho_thanh_toan', 'Chờ thanh toán'), ('dang_thuc_hien', 'Đang thực hiện'), ('hoan_thanh', 'Hoàn thành')], default='chon_hoa', max_length=20),
        ),
    ]
