# Generated by Django 6.0.3 on 2026-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_dathoa', '0004_alter_donhang_trangthaidonhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiemhoaprofile',
            name='bank_bin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
