# Generated by Django 6.0.3 on 2026-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_dathoa', '0005_tiemhoaprofile_bank_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiemhoaprofile',
            name='hinhAnhSanPham_2',
            field=models.ImageField(blank=True, null=True, upload_to='shop_products/'),
        ),
        migrations.AddField(
            model_name='tiemhoaprofile',
            name='hinhAnhSanPham_3',
            field=models.ImageField(blank=True, null=True, upload_to='shop_products/'),
        ),
        migrations.AddField(
            model_name='tiemhoaprofile',
            name='hinhAnhSanPham_4',
            field=models.ImageField(blank=True, null=True, upload_to='shop_products/'),
        ),
    ]
