# Generated by Django 6.0.3 on 2026-04-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_dathoa', '0007_shopgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopgalleryimage',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
